version: "3.5"
services:
  mini-admin-server:
    image: server:1.0.0
    build: ./server
    volumes:
      - ./server:/usr/src/app
    environment:
      - TZ=Asia/Shanghai
    ports:
        - 3000:3000
  mini-admin-web:
    image: nginx:1.14.1
    restart: always
    volumes:
      - ./server/dist:/usr/share/nginx/html
    ports:
      - 8000:80
